spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  liquibase:
    enabled: false
server:
  port: 8081

logging:
  level:
    org.springframework.mail: WARN
    org.springframework.security: WARN
    
jwt:
  signerKey: "test-signer-key-z8q/gnCQ3bJb4RWbC36UuznGJ0QNpnn1NSJuYO+nU0QWHPtgJE0y6BO3L2ZNZXnB"
  valid-duration: 900
  refreshable-duration: 604800
app:
  timezone: Asia/Ho_Chi_Minh