/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VocabIndexRouteImport } from './routes/vocab/index'
import { Route as LeaderboardIndexRouteImport } from './routes/leaderboard/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VocabFlashcardRouteImport } from './routes/vocab/flashcard'
import { Route as QuizSetupRouteImport } from './routes/quiz/setup'
import { Route as QuizCollectionIdRouteImport } from './routes/quiz/$collectionId'
import { Route as AuthenticationVerifyRouteImport } from './routes/authentication/verify'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google-callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as UserTopicsIndexRouteImport } from './routes/user/topics/index'
import { Route as UserProfileIndexRouteImport } from './routes/user/profile/index'
import { Route as UserLevelIndexRouteImport } from './routes/user/level/index'
import { Route as UserLessonsIndexRouteImport } from './routes/user/lessons/index'
import { Route as UserLessonDiscoveryIndexRouteImport } from './routes/user/lesson-discovery/index'
import { Route as UserCustomTopicsIndexRouteImport } from './routes/user/custom-topics/index'
import { Route as UserCustomLessonsIndexRouteImport } from './routes/user/custom-lessons/index'
import { Route as AdminUserIndexRouteImport } from './routes/admin/user/index'
import { Route as AdminTopicIndexRouteImport } from './routes/admin/topic/index'
import { Route as AdminLevelIndexRouteImport } from './routes/admin/level/index'
import { Route as AdminLessonIndexRouteImport } from './routes/admin/lesson/index'
import { Route as AdminLanguageIndexRouteImport } from './routes/admin/language/index'
import { Route as AdminHistoryIndexRouteImport } from './routes/admin/history/index'
import { Route as UserLessonPracticeLessonIdRouteImport } from './routes/user/lesson-practice/$lessonId'
import { Route as UserLessonDiscoveryLessonRouteImport } from './routes/user/lesson-discovery/lesson'
import { Route as AuthVerifyEmailTokenRouteImport } from './routes/auth/verify-email/$token'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/auth/reset-password/$token'

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabIndexRoute = VocabIndexRouteImport.update({
  id: '/vocab/',
  path: '/vocab/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const VocabFlashcardRoute = VocabFlashcardRouteImport.update({
  id: '/vocab/flashcard',
  path: '/vocab/flashcard',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSetupRoute = QuizSetupRouteImport.update({
  id: '/quiz/setup',
  path: '/quiz/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCollectionIdRoute = QuizCollectionIdRouteImport.update({
  id: '/quiz/$collectionId',
  path: '/quiz/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationVerifyRoute = AuthenticationVerifyRouteImport.update({
  id: '/authentication/verify',
  path: '/authentication/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/google-callback',
  path: '/google-callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => AuthRouteRoute,
} as any)
const UserTopicsIndexRoute = UserTopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserProfileIndexRoute = UserProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserLevelIndexRoute = UserLevelIndexRouteImport.update({
  id: '/level/',
  path: '/level/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserLessonsIndexRoute = UserLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserLessonDiscoveryIndexRoute =
  UserLessonDiscoveryIndexRouteImport.update({
    id: '/lesson-discovery/',
    path: '/lesson-discovery/',
    getParentRoute: () => UserRouteRoute,
  } as any)
const UserCustomTopicsIndexRoute = UserCustomTopicsIndexRouteImport.update({
  id: '/custom-topics/',
  path: '/custom-topics/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserCustomLessonsIndexRoute = UserCustomLessonsIndexRouteImport.update({
  id: '/custom-lessons/',
  path: '/custom-lessons/',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminUserIndexRoute = AdminUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTopicIndexRoute = AdminTopicIndexRouteImport.update({
  id: '/topic/',
  path: '/topic/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLevelIndexRoute = AdminLevelIndexRouteImport.update({
  id: '/level/',
  path: '/level/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLessonIndexRoute = AdminLessonIndexRouteImport.update({
  id: '/lesson/',
  path: '/lesson/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLanguageIndexRoute = AdminLanguageIndexRouteImport.update({
  id: '/language/',
  path: '/language/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHistoryIndexRoute = AdminHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserLessonPracticeLessonIdRoute =
  UserLessonPracticeLessonIdRouteImport.update({
    id: '/lesson-practice/$lessonId',
    path: '/lesson-practice/$lessonId',
    getParentRoute: () => UserRouteRoute,
  } as any)
const UserLessonDiscoveryLessonRoute =
  UserLessonDiscoveryLessonRouteImport.update({
    id: '/lesson-discovery/lesson',
    path: '/lesson-discovery/lesson',
    getParentRoute: () => UserRouteRoute,
  } as any)
const AuthVerifyEmailTokenRoute = AuthVerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/authentication/verify': typeof AuthenticationVerifyRoute
  '/quiz/$collectionId': typeof QuizCollectionIdRoute
  '/quiz/setup': typeof QuizSetupRoute
  '/vocab/flashcard': typeof VocabFlashcardRoute
  '/admin/': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/vocab': typeof VocabIndexRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify-email/$token': typeof AuthVerifyEmailTokenRoute
  '/user/lesson-discovery/lesson': typeof UserLessonDiscoveryLessonRoute
  '/user/lesson-practice/$lessonId': typeof UserLessonPracticeLessonIdRoute
  '/admin/history': typeof AdminHistoryIndexRoute
  '/admin/language': typeof AdminLanguageIndexRoute
  '/admin/lesson': typeof AdminLessonIndexRoute
  '/admin/level': typeof AdminLevelIndexRoute
  '/admin/topic': typeof AdminTopicIndexRoute
  '/admin/user': typeof AdminUserIndexRoute
  '/user/custom-lessons': typeof UserCustomLessonsIndexRoute
  '/user/custom-topics': typeof UserCustomTopicsIndexRoute
  '/user/lesson-discovery': typeof UserLessonDiscoveryIndexRoute
  '/user/lessons': typeof UserLessonsIndexRoute
  '/user/level': typeof UserLevelIndexRoute
  '/user/profile': typeof UserProfileIndexRoute
  '/user/topics': typeof UserTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/authentication/verify': typeof AuthenticationVerifyRoute
  '/quiz/$collectionId': typeof QuizCollectionIdRoute
  '/quiz/setup': typeof QuizSetupRoute
  '/vocab/flashcard': typeof VocabFlashcardRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/vocab': typeof VocabIndexRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify-email/$token': typeof AuthVerifyEmailTokenRoute
  '/user/lesson-discovery/lesson': typeof UserLessonDiscoveryLessonRoute
  '/user/lesson-practice/$lessonId': typeof UserLessonPracticeLessonIdRoute
  '/admin/history': typeof AdminHistoryIndexRoute
  '/admin/language': typeof AdminLanguageIndexRoute
  '/admin/lesson': typeof AdminLessonIndexRoute
  '/admin/level': typeof AdminLevelIndexRoute
  '/admin/topic': typeof AdminTopicIndexRoute
  '/admin/user': typeof AdminUserIndexRoute
  '/user/custom-lessons': typeof UserCustomLessonsIndexRoute
  '/user/custom-topics': typeof UserCustomTopicsIndexRoute
  '/user/lesson-discovery': typeof UserLessonDiscoveryIndexRoute
  '/user/lessons': typeof UserLessonsIndexRoute
  '/user/level': typeof UserLevelIndexRoute
  '/user/profile': typeof UserProfileIndexRoute
  '/user/topics': typeof UserTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/authentication/verify': typeof AuthenticationVerifyRoute
  '/quiz/$collectionId': typeof QuizCollectionIdRoute
  '/quiz/setup': typeof QuizSetupRoute
  '/vocab/flashcard': typeof VocabFlashcardRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/vocab/': typeof VocabIndexRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify-email/$token': typeof AuthVerifyEmailTokenRoute
  '/user/lesson-discovery/lesson': typeof UserLessonDiscoveryLessonRoute
  '/user/lesson-practice/$lessonId': typeof UserLessonPracticeLessonIdRoute
  '/admin/history/': typeof AdminHistoryIndexRoute
  '/admin/language/': typeof AdminLanguageIndexRoute
  '/admin/lesson/': typeof AdminLessonIndexRoute
  '/admin/level/': typeof AdminLevelIndexRoute
  '/admin/topic/': typeof AdminTopicIndexRoute
  '/admin/user/': typeof AdminUserIndexRoute
  '/user/custom-lessons/': typeof UserCustomLessonsIndexRoute
  '/user/custom-topics/': typeof UserCustomTopicsIndexRoute
  '/user/lesson-discovery/': typeof UserLessonDiscoveryIndexRoute
  '/user/lessons/': typeof UserLessonsIndexRoute
  '/user/level/': typeof UserLevelIndexRoute
  '/user/profile/': typeof UserProfileIndexRoute
  '/user/topics/': typeof UserTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/user'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/google-callback'
    | '/auth/login'
    | '/auth/register'
    | '/authentication/verify'
    | '/quiz/$collectionId'
    | '/quiz/setup'
    | '/vocab/flashcard'
    | '/admin/'
    | '/collections'
    | '/leaderboard'
    | '/vocab'
    | '/auth/reset-password/$token'
    | '/auth/verify-email/$token'
    | '/user/lesson-discovery/lesson'
    | '/user/lesson-practice/$lessonId'
    | '/admin/history'
    | '/admin/language'
    | '/admin/lesson'
    | '/admin/level'
    | '/admin/topic'
    | '/admin/user'
    | '/user/custom-lessons'
    | '/user/custom-topics'
    | '/user/lesson-discovery'
    | '/user/lessons'
    | '/user/level'
    | '/user/profile'
    | '/user/topics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/user'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/google-callback'
    | '/auth/login'
    | '/auth/register'
    | '/authentication/verify'
    | '/quiz/$collectionId'
    | '/quiz/setup'
    | '/vocab/flashcard'
    | '/admin'
    | '/collections'
    | '/leaderboard'
    | '/vocab'
    | '/auth/reset-password/$token'
    | '/auth/verify-email/$token'
    | '/user/lesson-discovery/lesson'
    | '/user/lesson-practice/$lessonId'
    | '/admin/history'
    | '/admin/language'
    | '/admin/lesson'
    | '/admin/level'
    | '/admin/topic'
    | '/admin/user'
    | '/user/custom-lessons'
    | '/user/custom-topics'
    | '/user/lesson-discovery'
    | '/user/lessons'
    | '/user/level'
    | '/user/profile'
    | '/user/topics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/user'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/google-callback'
    | '/auth/login'
    | '/auth/register'
    | '/authentication/verify'
    | '/quiz/$collectionId'
    | '/quiz/setup'
    | '/vocab/flashcard'
    | '/admin/'
    | '/collections/'
    | '/leaderboard/'
    | '/vocab/'
    | '/auth/reset-password/$token'
    | '/auth/verify-email/$token'
    | '/user/lesson-discovery/lesson'
    | '/user/lesson-practice/$lessonId'
    | '/admin/history/'
    | '/admin/language/'
    | '/admin/lesson/'
    | '/admin/level/'
    | '/admin/topic/'
    | '/admin/user/'
    | '/user/custom-lessons/'
    | '/user/custom-topics/'
    | '/user/lesson-discovery/'
    | '/user/lessons/'
    | '/user/level/'
    | '/user/profile/'
    | '/user/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AuthenticationVerifyRoute: typeof AuthenticationVerifyRoute
  QuizCollectionIdRoute: typeof QuizCollectionIdRoute
  QuizSetupRoute: typeof QuizSetupRoute
  VocabFlashcardRoute: typeof VocabFlashcardRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
  VocabIndexRoute: typeof VocabIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab/': {
      id: '/vocab/'
      path: '/vocab'
      fullPath: '/vocab'
      preLoaderRoute: typeof VocabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/vocab/flashcard': {
      id: '/vocab/flashcard'
      path: '/vocab/flashcard'
      fullPath: '/vocab/flashcard'
      preLoaderRoute: typeof VocabFlashcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/setup': {
      id: '/quiz/setup'
      path: '/quiz/setup'
      fullPath: '/quiz/setup'
      preLoaderRoute: typeof QuizSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$collectionId': {
      id: '/quiz/$collectionId'
      path: '/quiz/$collectionId'
      fullPath: '/quiz/$collectionId'
      preLoaderRoute: typeof QuizCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/verify': {
      id: '/authentication/verify'
      path: '/authentication/verify'
      fullPath: '/authentication/verify'
      preLoaderRoute: typeof AuthenticationVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/google-callback': {
      id: '/auth/google-callback'
      path: '/google-callback'
      fullPath: '/auth/google-callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/user/topics/': {
      id: '/user/topics/'
      path: '/topics'
      fullPath: '/user/topics'
      preLoaderRoute: typeof UserTopicsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/profile/': {
      id: '/user/profile/'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/level/': {
      id: '/user/level/'
      path: '/level'
      fullPath: '/user/level'
      preLoaderRoute: typeof UserLevelIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/lessons/': {
      id: '/user/lessons/'
      path: '/lessons'
      fullPath: '/user/lessons'
      preLoaderRoute: typeof UserLessonsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/lesson-discovery/': {
      id: '/user/lesson-discovery/'
      path: '/lesson-discovery'
      fullPath: '/user/lesson-discovery'
      preLoaderRoute: typeof UserLessonDiscoveryIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/custom-topics/': {
      id: '/user/custom-topics/'
      path: '/custom-topics'
      fullPath: '/user/custom-topics'
      preLoaderRoute: typeof UserCustomTopicsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/custom-lessons/': {
      id: '/user/custom-lessons/'
      path: '/custom-lessons'
      fullPath: '/user/custom-lessons'
      preLoaderRoute: typeof UserCustomLessonsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/admin/user/': {
      id: '/admin/user/'
      path: '/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/topic/': {
      id: '/admin/topic/'
      path: '/topic'
      fullPath: '/admin/topic'
      preLoaderRoute: typeof AdminTopicIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/level/': {
      id: '/admin/level/'
      path: '/level'
      fullPath: '/admin/level'
      preLoaderRoute: typeof AdminLevelIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lesson/': {
      id: '/admin/lesson/'
      path: '/lesson'
      fullPath: '/admin/lesson'
      preLoaderRoute: typeof AdminLessonIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/language/': {
      id: '/admin/language/'
      path: '/language'
      fullPath: '/admin/language'
      preLoaderRoute: typeof AdminLanguageIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/history/': {
      id: '/admin/history/'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/user/lesson-practice/$lessonId': {
      id: '/user/lesson-practice/$lessonId'
      path: '/lesson-practice/$lessonId'
      fullPath: '/user/lesson-practice/$lessonId'
      preLoaderRoute: typeof UserLessonPracticeLessonIdRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/lesson-discovery/lesson': {
      id: '/user/lesson-discovery/lesson'
      path: '/lesson-discovery/lesson'
      fullPath: '/user/lesson-discovery/lesson'
      preLoaderRoute: typeof UserLessonDiscoveryLessonRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/auth/verify-email/$token': {
      id: '/auth/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/auth/verify-email/$token'
      preLoaderRoute: typeof AuthVerifyEmailTokenRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminHistoryIndexRoute: typeof AdminHistoryIndexRoute
  AdminLanguageIndexRoute: typeof AdminLanguageIndexRoute
  AdminLessonIndexRoute: typeof AdminLessonIndexRoute
  AdminLevelIndexRoute: typeof AdminLevelIndexRoute
  AdminTopicIndexRoute: typeof AdminTopicIndexRoute
  AdminUserIndexRoute: typeof AdminUserIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminHistoryIndexRoute: AdminHistoryIndexRoute,
  AdminLanguageIndexRoute: AdminLanguageIndexRoute,
  AdminLessonIndexRoute: AdminLessonIndexRoute,
  AdminLevelIndexRoute: AdminLevelIndexRoute,
  AdminTopicIndexRoute: AdminTopicIndexRoute,
  AdminUserIndexRoute: AdminUserIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
  AuthVerifyEmailTokenRoute: typeof AuthVerifyEmailTokenRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
  AuthVerifyEmailTokenRoute: AuthVerifyEmailTokenRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserLessonDiscoveryLessonRoute: typeof UserLessonDiscoveryLessonRoute
  UserLessonPracticeLessonIdRoute: typeof UserLessonPracticeLessonIdRoute
  UserCustomLessonsIndexRoute: typeof UserCustomLessonsIndexRoute
  UserCustomTopicsIndexRoute: typeof UserCustomTopicsIndexRoute
  UserLessonDiscoveryIndexRoute: typeof UserLessonDiscoveryIndexRoute
  UserLessonsIndexRoute: typeof UserLessonsIndexRoute
  UserLevelIndexRoute: typeof UserLevelIndexRoute
  UserProfileIndexRoute: typeof UserProfileIndexRoute
  UserTopicsIndexRoute: typeof UserTopicsIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserLessonDiscoveryLessonRoute: UserLessonDiscoveryLessonRoute,
  UserLessonPracticeLessonIdRoute: UserLessonPracticeLessonIdRoute,
  UserCustomLessonsIndexRoute: UserCustomLessonsIndexRoute,
  UserCustomTopicsIndexRoute: UserCustomTopicsIndexRoute,
  UserLessonDiscoveryIndexRoute: UserLessonDiscoveryIndexRoute,
  UserLessonsIndexRoute: UserLessonsIndexRoute,
  UserLevelIndexRoute: UserLevelIndexRoute,
  UserProfileIndexRoute: UserProfileIndexRoute,
  UserTopicsIndexRoute: UserTopicsIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  AuthenticationVerifyRoute: AuthenticationVerifyRoute,
  QuizCollectionIdRoute: QuizCollectionIdRoute,
  QuizSetupRoute: QuizSetupRoute,
  VocabFlashcardRoute: VocabFlashcardRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
  VocabIndexRoute: VocabIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
