spring:
  application:
    name: translate-practice
  datasource:
    url: jdbc:postgresql://localhost:5432/lmh
    username: postgres
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  liquibase:
    enabled: true
    change-log: db/changelog/db-changelog.xml
    default-schema: public
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 35790031845-c8n8krgp3rs5464q0dt7tlj74ps79kmb.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8081/login/oauth2/code/google

            scope:
              - openid
              - profile
              - email
  mail:
    host: smtp.gmail.com
    port: 587
    username: hocnguyen1102.work@gmail.com
    password: khus plsi hvgh peqz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: default

# Cloudinary Configuration
cloudinary:
  cloud_name: dzvxgyg88
  api_key: 281855212738654
  api_secret: CBx98FIol43xihZJt0fX1AKgt9E
jwt:
  signerKey: "z8q/gnCQ3bJb4RWbC36UuznGJ0QNpnn1NSJuYO+nU0QWHPtgJE0y6BO3L2ZNZXnB"
  valid-duration: 90000
  refreshable-duration: 604800
  api_secret: CBx98FIol43xihZJt0fX1AKgt9E

app:
  base-url: http://localhost:80
  verification:
    token:
      expiry: 86400000
  timezone: Asia/Ho_Chi_Minh

server:
  port: 8081

logging:
  level:
    org.springframework.mail: DEBUG

